name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Check C code formatting
        run: find . \( -name "*.c" -o -name "*.h" \) -print0 | xargs -0 clang-format --dry-run --Werror

      - name: Check Zig code formatting
        run: zig fmt --check .

  test-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Run tests (data)
        run: zig build test-data --summary all

  test-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run tests (lib)
        run: |
          docker build --platform linux/386 -t hashab:latest .
          docker run --rm --platform linux/386 hashab:latest

  test-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.5

      - name: Build wasm
        run: zig build wasm

      - name: Run tests (wasm)
        run: bun test
